export const site = {
  name: "gcanva.art",
  url: "https://www.gcanva.art",
  title: "Guillaume Canva, développeur web et artiste visuel",
  description:
    "Guillaume Canva, à Tournai : intégration web dans le Studio, dessins et expérimentations dans le Carnet. L’interstice entre les deux, sur gcanva.art.",
  person: "Guillaume Canva",
  givenName: "Guillaume",
  familyName: "Canva",
  jobTitle: "Développeur web et artiste visuel",
  locality: "Tournai",
  region: "Hainaut",
  country: "BE",
  email: "guillaume.canva@gmail.com",
  studioUrl: "https://studio.gcanva.art",
  carnetUrl: "https://carnet.gcanva.art",
  chauffageUrl: "https://www.tournai-chauffage.be",
  /* Portrait publié sur le studio ; réutilisé ici pour que les trois sites montrent la même personne. */
  portraitUrl: "https://cdn.sanity.io/images/l3lfckoz/production/311dd6bd45b0b5a94a1806db39cc9b0795818581-2528x2528.jpg",
  /* Premier commit du dépôt, et dernière révision du contenu de la page. À mettre à jour quand le texte change. */
  dateCreated: "2026-02-18",
  dateModified: "2026-10-09",
} as const

const ids = {
  person: `${site.url}/#guillaume-canva`,
  website: `${site.url}/#website`,
  page: `${site.url}/#webpage`,
  studio: `${site.studioUrl}/#studio`,
  studioSite: `${site.studioUrl}/#website`,
  carnetSite: `${site.carnetUrl}/#website`,
  carnetBlog: `${site.carnetUrl}/#blog`,
  works: `${site.url}/#realisations`,
  services: `${site.studioUrl}/#services`,
} as const

const address = {
  "@type": "PostalAddress",
  addressLocality: site.locality,
  addressRegion: site.region,
  addressCountry: site.country,
}

const services = [
  {
    name: "Intégration web UI/UX",
    description: "Transformer des maquettes Figma ou Canva en interfaces interactives, fidèles au pixel et à l’expérience des visiteurs.",
  },
  {
    name: "Optimisation et performance",
    description: "Rendre un site rapide sur mobile, accessible et lisible par les moteurs de recherche.",
  },
  {
    name: "Maintenance évolutive",
    description: "Faire évoluer un site dans la durée sans accumuler de dette technique.",
  },
] as const

export const jsonLd = {
  "@context": "https://schema.org",
  "@graph": [
    {
      "@type": "Person",
      "@id": ids.person,
      name: site.person,
      givenName: site.givenName,
      familyName: site.familyName,
      url: site.url,
      image: {
        "@type": "ImageObject",
        url: site.portraitUrl,
        contentUrl: site.portraitUrl,
        width: 2528,
        height: 2528,
        caption: site.person,
      },
      email: `mailto:${site.email}`,
      jobTitle: site.jobTitle,
      description: site.description,
      address,
      homeLocation: {
        "@type": "Place",
        name: `${site.locality}, Belgique`,
        address,
      },
      hasOccupation: [
        {
          "@type": "Occupation",
          name: "Développeur web",
          description: "Intégration, performance et maintenance de sites web.",
          occupationLocation: { "@type": "City", name: site.locality },
          skills: ["Intégration web", "Performance web", "Accessibilité", "Ergonomie", "SEO technique"],
        },
        {
          "@type": "Occupation",
          name: "Artiste visuel",
          description: "Dessin, peinture acrylique et expérimentations visuelles.",
          occupationLocation: { "@type": "City", name: site.locality },
          skills: ["Dessin", "Peinture acrylique", "Infographie", "Illustration textile"],
        },
      ],
      worksFor: { "@id": ids.studio },
      knowsAbout: ["Intégration web", "Performance web", "Ergonomie", "Accessibilité", "Dessin", "Peinture"],
      knowsLanguage: ["fr"],
      mainEntityOfPage: { "@id": ids.page },
      subjectOf: { "@id": ids.page },
      sameAs: [site.studioUrl, site.carnetUrl],
    },
    {
      "@type": "ProfessionalService",
      "@id": ids.studio,
      name: "Studio gcanva.art",
      alternateName: "Artisan Web — Guillaume Canva",
      url: site.studioUrl,
      email: `mailto:${site.email}`,
      description:
        "Studio d’intégration web à Tournai : interfaces fidèles aux maquettes, performance, accessibilité et maintenance, en collaboration directe.",
      image: site.portraitUrl,
      address,
      areaServed: [
        { "@type": "City", name: site.locality },
        { "@type": "Country", name: "Belgique" },
      ],
      founder: { "@id": ids.person },
      employee: { "@id": ids.person },
      knowsLanguage: ["fr"],
      hasOfferCatalog: {
        "@type": "OfferCatalog",
        "@id": ids.services,
        name: "Services du studio",
        itemListElement: services.map((service, index) => ({
          "@type": "Offer",
          position: index + 1,
          itemOffered: {
            "@type": "Service",
            name: service.name,
            description: service.description,
            provider: { "@id": ids.studio },
            areaServed: { "@type": "Country", name: "Belgique" },
          },
        })),
      },
      sameAs: [site.url],
    },
    {
      "@type": "WebSite",
      "@id": ids.website,
      url: site.url,
      name: site.name,
      alternateName: "L’Interstice",
      description: site.description,
      inLanguage: "fr-BE",
      publisher: { "@id": ids.person },
      about: { "@id": ids.person },
      hasPart: [{ "@id": ids.studioSite }, { "@id": ids.carnetSite }],
    },
    {
      "@type": "WebSite",
      "@id": ids.studioSite,
      url: site.studioUrl,
      name: "Studio gcanva.art",
      description: "La technique au service du besoin : intégration, ergonomie, projets professionnels.",
      inLanguage: "fr-BE",
      publisher: { "@id": ids.person },
      about: { "@id": ids.studio },
      isPartOf: { "@id": ids.website },
    },
    {
      "@type": "WebSite",
      "@id": ids.carnetSite,
      url: site.carnetUrl,
      name: "Carnet gcanva.art",
      description: "Dessins, peintures et expérimentations visuelles de Guillaume Canva.",
      inLanguage: "fr-BE",
      publisher: { "@id": ids.person },
      isPartOf: { "@id": ids.website },
      hasPart: { "@id": ids.carnetBlog },
    },
    {
      "@type": "Blog",
      "@id": ids.carnetBlog,
      url: site.carnetUrl,
      name: "Carnet gcanva.art",
      author: { "@id": ids.person },
      inLanguage: "fr-BE",
    },
    {
      "@type": "ProfilePage",
      "@id": ids.page,
      url: site.url,
      name: site.title,
      description: site.description,
      inLanguage: "fr-BE",
      dateCreated: site.dateCreated,
      dateModified: site.dateModified,
      isPartOf: { "@id": ids.website },
      mainEntity: { "@id": ids.person },
      about: { "@id": ids.person },
      primaryImageOfPage: {
        "@type": "ImageObject",
        url: `${site.url}/opengraph-image`,
        width: 1200,
        height: 630,
      },
      hasPart: { "@id": ids.works },
      relatedLink: [site.studioUrl, site.carnetUrl],
    },
    {
      "@type": "ItemList",
      "@id": ids.works,
      name: "Réalisations",
      itemListOrder: "https://schema.org/ItemListUnordered",
      numberOfItems: 2,
      itemListElement: [
        {
          "@type": "ListItem",
          position: 1,
          item: {
            "@type": "WebSite",
            name: "Tournai Chauffage",
            url: site.chauffageUrl,
            description: "Site vitrine réalisé par le studio.",
            genre: "Site vitrine",
            creator: { "@id": ids.person },
            provider: { "@id": ids.studio },
            inLanguage: "fr-BE",
          },
        },
        {
          "@type": "ListItem",
          position: 2,
          item: {
            "@type": "CreativeWork",
            name: "Infirmière à domicile",
            description: "Maquette web d’un site pour une infirmière à domicile.",
            genre: "Maquette web",
            creator: { "@id": ids.person },
            provider: { "@id": ids.studio },
            inLanguage: "fr-BE",
          },
        },
      ],
    },
  ],
}
